spring:
  profiles:
    #active: local, redis
    active: local, local cache

---
# DATABASE
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/sbb
    driver-class-name: org.postgresql.Driver
    username: web
    password: web
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    hibernate:
#       ddl-auto: create
      ddl-auto: update
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

jwt:
  header: Authorization
  secret: and0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdpLWp3dC10ZXN0LWFsamphYmFlZ2ktand0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdpLWp3dC10ZXN0LWFsamphYmFlZ2ktand0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdp
  token-validity-in-seconds: 86400

rigo:
  node-url: http://192.168.252.60:26657/
  node-socket: ws://192.168.252.60:26657/websocket

server:
  error:
    whitelabel:
      enabled: false
  port: 8881
