spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        metadata-builder-contributor: io.medium.poc.common.dialect.CustomMariaDBDialect
        format_sql: true
        generate_statistics: false
        use_sql_comments: true
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  datasource:
    url: jdbc:mariadb://crudcm.co.kr:3306/stopoc
    username: stopoc
    password: stopoc1234##
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-test-query: 'select 1'
      connection-timeout: 10000 # 10 sec.
      maximum-pool-size: 10
      pool-name: ibk-sto-pool

# logging
logging:
  level:
    root: INFO
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
      springframework: INFO
    io:
      medium:
        poc: DEBUG

server:
  error:
    whitelabel:
      enabled: false
  port: 8088
  servlet:
    encoding:
      charset: UTF-8
      force: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /ibk-sto-poc
    defaultModelsExpandDepth: -1
    tagsSorter: alpha

feign:
  client:
    config:
      ksd:
        connectTimeout: 10000 # 10?
        readTimeout: 10000 # 10?
        url: http://localhost:8088/api/poc/ksd
      isr:
        connectTimeout: 10000 # 10?
        readTimeout: 10000 # 10?
        url: http://localhost:8088/api/poc/isr
      mdlpay:
        connectTimeout: 10000 # 10?
        readTimeout: 10000 # 10?
        url: http://rtcdev.ddns.net:9991/invoke/paychannel
---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        metadata-builder-contributor: io.medium.poc.common.dialect.CustomMariaDBDialect
        format_sql: true
        generate_statistics: false
        use_sql_comments: true
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  datasource:
    url: jdbc:mariadb://crudcm.co.kr:3306/stopoc
    username: stopoc
    password: stopoc1234##
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-test-query: 'select 1'
      connection-timeout: 10000 # 10 sec.
      maximum-pool-size: 10
      pool-name: ibk-sto-pool

# logging
logging:
  level:
    root: INFO
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
      springframework: INFO
    io:
      medium:
        poc: DEBUG

server:
  error:
    whitelabel:
      enabled: false
  port: 8088
  servlet:
    encoding:
      charset: UTF-8
      force: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /ibk-sto-poc
    defaultModelsExpandDepth: -1
    tagsSorter: alpha

feign:
  client:
    config:
      ksd:
        connectTimeout: 10000 # 10?
        readTimeout: 10000 # 10?
        url: http://3.38.162.213:8088/api/poc/ksd
      isr:
        connectTimeout: 10000 # 10?
        readTimeout: 10000 # 10?
        url: http://3.38.162.213:8088/api/poc/isr
      mdlpay:
        connectTimeout: 10000 # 10?
        readTimeout: 10000 # 10?
        url: http://rtcdev.ddns.net:9991/invoke/paychannel