spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local

rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest
  exchange: basquiat
  virtual-host: /
  db-queue: db-chk
  db-routing-key: db
  log-queue: log-message
  log-routing-key: log

server:
  error:
    whitelabel:
      enabled: false
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      force: true